[build]
builder = "nixpacks"
buildCommand = "npm install"
watchPatterns = ["frontend/**"]

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["nodejs", "npm"]
